apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spark-master-ingress
  namespace: platform
  annotations:
    kubernetes.io/ingress.class: nginx
    # --- ลบบรรทัด rewrite-target ทิ้งไปเลยครับ ---
    # nginx.ingress.kubernetes.io/rewrite-target: /  <-- ลบตัวนี้
spec:
  rules:
    - host: spark.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spark-master-svc
                port:
                  number: 8080