# --- แก้ไข Service ---
apiVersion: v1
kind: Service
metadata:
  name: spark-master-svc  
  namespace: platform          # <--- ระบุ Namespace ให้ชัดเจน# <--- เปลี่ยนชื่อตรงนี้ (เดิมคือ spark-master)
spec:
  type: NodePort
  ports:
    - port: 8080
      name: webui
      nodePort: 31008
    - port: 7077
      name: master
      nodePort: 31009
  selector:
    app: spark-master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  namespace: platform          # <--- ระบุ Namespace ให้ชัดเจน
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
        - name: spark-master
          image: warvba22/spark:1.0.0  
          command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
          ports:
            - containerPort: 7077
            - containerPort: 8080
          env:
            - name: SPARK_NO_DAEMONIZE
              value: "true"
          volumeMounts:
            - name: spark-apps
              mountPath: /opt/spark-apps
      volumes:
        - name: spark-apps
          hostPath:
            path: /data/spark-apps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  namespace: platform          # <--- ระบุ Namespace ให้ชัดเจน
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: warvba22/spark:1.0.0 
          command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master-svc:7077"]
          env:
            - name: SPARK_WORKER_CORES
              value: "1"
            - name: SPARK_WORKER_MEMORY
              value: "1G"
            - name: SPARK_NO_DAEMONIZE
              value: "true"
          volumeMounts:
            - name: spark-apps
              mountPath: /opt/spark-apps
      volumes:
        - name: spark-apps
          hostPath:
            path: /data/spark-apps

            